locales:
  en:
    name: Votic Keyboards
    description: Mobile OS keyboards for the Votic language from the Divvun group at UiT.
  nb:
    name: Votic tastatur
    description: Mobiltastatur for Votic fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
